### ISSUE TITLE
bind failed: EADDRINUSE (Address already in use)

### ISSUE THREAD

**Issue by minarja1** [donfuxx/Mockinizer#31]
Hi,

I added some mocks to my OkHttpClientBuilder and I'm getting this error. Is this a bug, or am I doing something wrong? I just create a typical OkHttpBuilder with some interceptors like this:

`val cookieJar = PersistentCookieJar(SetCookieCache(), SharedPrefsCookiePersistor(context))
    val okHttpClient = OkHttpClient.Builder()
        .addInterceptor {
            val request = it
                .request()
                .newBuilder()
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .addHeader("Accept-Language", Locale.getDefault().toLanguageTag())
                .addHeader("Content-Language", Locale.getDefault().toLanguageTag())
                .addHeader("X-App-Language", Locale.getDefault().language)
                .addHeader("appType", Constants.appType)
            it.proceed(request.build())
        }
        .addInterceptor(hostInterceptor)
        .addInterceptor(ConnectivityInterceptor(context))
        .connectTimeout(15, TimeUnit.SECONDS)
        .readTimeout(240, TimeUnit.SECONDS)
        .writeTimeout(90, TimeUnit.SECONDS)
        .cookieJar(cookieJar)
`

 and then call

`builder.mockinize(mocks)`

My mocks look something like this: 

`val mocks: Map<RequestFilter, MockResponse> = mapOf(
    RequestFilter(
        "/endpoint",
        headers = Headers.headersOf(
            "Content-Type", "application/json",
            "Accept", "application/json",
            "Accept-Language", Locale.getDefault().toLanguageTag(),
            "Content-Language", Locale.getDefault().toLanguageTag(),
            "App-Type", "android"
        )
    ) to MockResponse().apply {
        setResponseCode(200)
        setBodyDelay(1, TimeUnit.SECONDS)
        setHeadersDelay(1, TimeUnit.SECONDS)
        setBody(
            Develop.loadMockData(
                "mock_reservation_success.json"
            )
        )
    },`...

the error I'm getting:

`2020-06-03 14:17:30.695 25141-25384/com.pelicantravel.pelipecky E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.pelicantravel.pelipecky, PID: 25141
    java.net.BindException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.IoBridge.bind(IoBridge.java:104)
        at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:149)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:393)
        at java.net.ServerSocket.bind(ServerSocket.java:376)
        at okhttp3.mockwebserver.MockWebServer.start(MockWebServer.kt:388)
        at okhttp3.mockwebserver.MockWebServer.start(MockWebServer.kt:370)
        at okhttp3.mockwebserver.MockWebServer.start(MockWebServer.kt:360)
        at com.appham.mockinizer.MockWebServerExtKt$configure$1.invokeSuspend(MockWebServerExt.kt:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.Linux.bind(Native Method)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:59)
        at libcore.io.IoBridge.bind(IoBridge.java:100)
        at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:149) 
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:393) 
        at java.net.ServerSocket.bind(ServerSocket.java:376) 
        at okhttp3.mockwebserver.MockWebServer.start(MockWebServer.kt:388) 
        at okhttp3.mockwebserver.MockWebServer.start(MockWebServer.kt:370) 
        at okhttp3.mockwebserver.MockWebServer.start(MockWebServer.kt:360) 
        at com.appham.mockinizer.MockWebServerExtKt$configure$1.invokeSuspend(MockWebServerExt.kt:12) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) `

**Comment by donfuxx** [comment]
Hi @minarja1  
The error "EADDRINUSE (Address already in use)" means that there is already some server running for the port that MockWebServer wants to use when trying to start it.
When you call `builder.mockinize(mocks)` then this will also start the MockWebServer (by default on port 34567). By looking at your stacktrace it seems that you call mockinize(mocks) 2 times which means the 2nd time the starting of the MockWebServer would fail, since it is already running. 
In theory you would only need to calll .mockinize(mocks) method only once, so I suggest reviewing your logic why this got called multiple times.
Alternatively you can also manually stop the MockWebServer by using the static method `Mockinizer.shutDown()` if you want to. It's also possible to provide a custom MockWebServer as the 2nd param in the .mockinize method if you really want to. So you could start MockWebServers on different ports for example.
I hope this helps. Let me know if that solves your issue.

**Comment by minarja1** [comment]
Hi,

you are correct, `mockinize()` was getting called multiple times in my use-case. Thank you for your answer!
